### ISSUE TITLE
schemaFile should allow to use any arbitrary location within project.rootDir

### ISSUE THREAD

**Issue by x80486** [edeandrea/xjc-generation-gradle-plugin#3]
Right now, `schemaFile` always prepend `${project.rootDir}/src/${sourceSet}/schemas/xjc/` to the provided string value. I think it should be straightforward to allow to use any location within `project.rootDir`.

**Comment by edeandrea** [comment]
Hi @x80486 thanks for the comment! I appreciate the interest!

This is something I honestly sat on the fence about when I did the implementation. What is here is a completely different implementation & DSL from what I had done in the past, but based on lessons learned from my previous experiences, as well as evolution in Gradle as a whole.

I always had the schemas located outside of any particular source set directory (something like a `misc/resources` folder). Over time I found that many of the teams I worked with kept asking to put the schemas somewhere within the source set that they belong to. I liked that idea so I went with it.

That being said I'm not opposed to allowing for additional flexibility if thats what the community wants. We'd have to figure out a way to do it that was backwards compatible.

My immediate thought (albeit without putting a whole lot of thought into it) would be to introduce another attribute on the schema DSL where you could specify a schema root directory, which would default to `$project.rootDir/src`. I'm open to thoughts/suggestions though.

**Comment by x80486** [comment]
I understand all of that...but I fail to comprehend why would these schemas (only used for code generation) are part of the project sources (or resources). I think about those as URIs: can be located anywhere.

**Comment by edeandrea** [comment]
I guess it's how you look at it. Nothing in `src/$sourceSet/schemas` is packaged with the application. There are many other libraries out there that use this paradigm (fabric8-maven-plugin comes to mind) where you can store kubernetes fragments in `src/$sourceSet/fabric8.` There are plenty of other conventions that use things like `src/$sourceSet/config` for things.

That being said I'm open to making a change so that it's more flexible if that's what's needed. I should have some cycles next week.

I'm open to contributions as well.

**Comment by edeandrea** [comment]
@x80486 I've implemented this one and will now work on the other one before publishing a new `1.1` version to the Gradle Plugin Portal.

Stay tuned!
